---
- hosts: localhost
  tasks:
    - name: Create a new file banners
      become: 'yes'
      become_method: sudo
      file:
        state: touch
        path: /etc/banners
        owner: root
        group: root
        mode: 0644

    - name: Add banners
      become: 'yes'
      become_method: sudo
      template:
        src: ../templates/etc/issue.j2
        dest: "{{ item }}"
        backup: 'no'
        mode: 0644
        owner: root
        group: root
      with_items:
        - /etc/banners
        - /etc/issue
        - /etc/issue.net
        - /etc/motd
      tags:
        - banners
        - security