---
- hosts: localhost
  tasks:
    - name: hosts.allow
      become: 'yes'
      become_method: sudo
      template:
        src: ../templates/etc/hosts.allow.j2
        dest: /etc/hosts.allow
        backup: 'no'
        mode: 0644
        owner: root
        group: root
      tags:
        - hosts.allow
        - security

    - name: hosts.deny
      become: 'yes'
      become_method: sudo
      template:
        src: ../templates/etc/hosts.deny.j2
        dest: /etc/hosts.deny
        backup: 'no'
        mode: 0644
        owner: root
        group: root
      tags:
        - hosts.deny
        - security