---
- hosts: localhost
  tasks:
    - name: modprobe_hardening1.conf
      become: 'yes'
      become_method: sudo
      file:
        state: touch
        path: /etc/modprobe.d/hardening1.conf
        owner: root
        group: root
        mode: 0644

    - include_vars: "../defaults/main.yml"

    - name: Disable kernel1 modules
      become: 'yes'
      become_method: sudo
      lineinfile:
        dest: /etc/modprobe.d/hardening1.conf
        line: "install {{ item }} /bin/true"
      with_items: "{{ kernel_blacklist_1 }}"
      tags:
        - modprobe
        - security

    - name: modprobe_hardening2.conf
      become: 'yes'
      become_method: sudo
      file:
        state: touch
        path: /etc/modprobe.d/hardening2.conf
        owner: root
        group: root
        mode: 0644

    - name: Disable kernel2 modules
      become: 'yes'
      become_method: sudo
      lineinfile:
        dest: /etc/modprobe.d/hardening2.conf
        line: "blacklist {{ item }}"
      with_items: "{{ kernel_blacklist_2 }}"
      tags:
        - modprobe
        - security