---
# A modifier selon vos souhaits.
- name: configure logindefs umask and pass
  become: 'yes'
  become_method: sudo
  template:
    src: /etc/logindefs.conf.j2
    dest: /etc/logindefs.conf
    backup: 'no'
    mode: 0644
    owner: root
    group: root
  tags:
    - umask
    - security